name: AreaPlanter
version: '1.4'
main: io.github.mrgucci1.areaPlanter.AreaPlanter
api-version: '1.21'
load: STARTUP
author: mrgucci1
description: Plants configurable areas of crops.
permissions:
  areaplanter.admin:
    default: op

